<?php
/**
 * Bill
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maviance\S3PApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Smobilpay S3P API
 *
 * Smobilpay Third Party API FOR PAYMENT COLLECTIONS
 *
 * OpenAPI spec version: 3.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Maviance\S3PApiClient\Model;

use \ArrayAccess;
use \Maviance\S3PApiClient\ObjectSerializer;

/**
 * Bill Class Doc Comment
 *
 * @category Class
 * @package  Maviance\S3PApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Bill implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Bill';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'billType' => 'string',
'penaltyAmount' => 'double',
'payOrder' => 'float',
'payItemId' => 'string',
'payItemDescr' => 'string',
'serviceNumber' => 'string',
'serviceid' => 'int',
'merchant' => 'string',
'amountType' => 'string',
'localCur' => 'string',
'amountLocalCur' => 'float',
'billNumber' => 'string',
'customerNumber' => 'string',
'billMonth' => 'string',
'billYear' => 'string',
'billDate' => '\DateTime',
'billDueDate' => '\DateTime',
'optStrg' => 'string',
'optNmb' => 'float'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'billType' => null,
'penaltyAmount' => 'double',
'payOrder' => null,
'payItemId' => null,
'payItemDescr' => null,
'serviceNumber' => null,
'serviceid' => null,
'merchant' => null,
'amountType' => null,
'localCur' => null,
'amountLocalCur' => 'float',
'billNumber' => null,
'customerNumber' => null,
'billMonth' => 'MM',
'billYear' => 'YYYY',
'billDate' => 'date',
'billDueDate' => 'date',
'optStrg' => null,
'optNmb' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'billType' => 'billType',
'penaltyAmount' => 'penaltyAmount',
'payOrder' => 'payOrder',
'payItemId' => 'payItemId',
'payItemDescr' => 'payItemDescr',
'serviceNumber' => 'serviceNumber',
'serviceid' => 'serviceid',
'merchant' => 'merchant',
'amountType' => 'amountType',
'localCur' => 'localCur',
'amountLocalCur' => 'amountLocalCur',
'billNumber' => 'billNumber',
'customerNumber' => 'customerNumber',
'billMonth' => 'billMonth',
'billYear' => 'billYear',
'billDate' => 'billDate',
'billDueDate' => 'billDueDate',
'optStrg' => 'optStrg',
'optNmb' => 'optNmb'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'billType' => 'setBillType',
'penaltyAmount' => 'setPenaltyAmount',
'payOrder' => 'setPayOrder',
'payItemId' => 'setPayItemId',
'payItemDescr' => 'setPayItemDescr',
'serviceNumber' => 'setServiceNumber',
'serviceid' => 'setServiceid',
'merchant' => 'setMerchant',
'amountType' => 'setAmountType',
'localCur' => 'setLocalCur',
'amountLocalCur' => 'setAmountLocalCur',
'billNumber' => 'setBillNumber',
'customerNumber' => 'setCustomerNumber',
'billMonth' => 'setBillMonth',
'billYear' => 'setBillYear',
'billDate' => 'setBillDate',
'billDueDate' => 'setBillDueDate',
'optStrg' => 'setOptStrg',
'optNmb' => 'setOptNmb'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'billType' => 'getBillType',
'penaltyAmount' => 'getPenaltyAmount',
'payOrder' => 'getPayOrder',
'payItemId' => 'getPayItemId',
'payItemDescr' => 'getPayItemDescr',
'serviceNumber' => 'getServiceNumber',
'serviceid' => 'getServiceid',
'merchant' => 'getMerchant',
'amountType' => 'getAmountType',
'localCur' => 'getLocalCur',
'amountLocalCur' => 'getAmountLocalCur',
'billNumber' => 'getBillNumber',
'customerNumber' => 'getCustomerNumber',
'billMonth' => 'getBillMonth',
'billYear' => 'getBillYear',
'billDate' => 'getBillDate',
'billDueDate' => 'getBillDueDate',
'optStrg' => 'getOptStrg',
'optNmb' => 'getOptNmb'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const BILL_TYPE_REGULAR = 'REGULAR';
    const BILL_TYPE_OVERDUE = 'OVERDUE';
    const AMOUNT_TYPE_FIXED = 'FIXED';
    const AMOUNT_TYPE_CUSTOM = 'CUSTOM';
    const AMOUNT_TYPE_PARTIAL = 'PARTIAL';
    const AMOUNT_TYPE_OVERPAY = 'OVERPAY';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBillTypeAllowableValues()
    {
        return [
            self::BILL_TYPE_REGULAR,
self::BILL_TYPE_OVERDUE,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAmountTypeAllowableValues()
    {
        return [
            self::AMOUNT_TYPE_FIXED,
self::AMOUNT_TYPE_CUSTOM,
self::AMOUNT_TYPE_PARTIAL,
self::AMOUNT_TYPE_OVERPAY,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['billType'] = isset($data['billType']) ? $data['billType'] : null;
        $this->container['penaltyAmount'] = isset($data['penaltyAmount']) ? $data['penaltyAmount'] : null;
        $this->container['payOrder'] = isset($data['payOrder']) ? $data['payOrder'] : null;
        $this->container['payItemId'] = isset($data['payItemId']) ? $data['payItemId'] : null;
        $this->container['payItemDescr'] = isset($data['payItemDescr']) ? $data['payItemDescr'] : null;
        $this->container['serviceNumber'] = isset($data['serviceNumber']) ? $data['serviceNumber'] : null;
        $this->container['serviceid'] = isset($data['serviceid']) ? $data['serviceid'] : null;
        $this->container['merchant'] = isset($data['merchant']) ? $data['merchant'] : null;
        $this->container['amountType'] = isset($data['amountType']) ? $data['amountType'] : null;
        $this->container['localCur'] = isset($data['localCur']) ? $data['localCur'] : null;
        $this->container['amountLocalCur'] = isset($data['amountLocalCur']) ? $data['amountLocalCur'] : null;
        $this->container['billNumber'] = isset($data['billNumber']) ? $data['billNumber'] : null;
        $this->container['customerNumber'] = isset($data['customerNumber']) ? $data['customerNumber'] : null;
        $this->container['billMonth'] = isset($data['billMonth']) ? $data['billMonth'] : null;
        $this->container['billYear'] = isset($data['billYear']) ? $data['billYear'] : null;
        $this->container['billDate'] = isset($data['billDate']) ? $data['billDate'] : null;
        $this->container['billDueDate'] = isset($data['billDueDate']) ? $data['billDueDate'] : null;
        $this->container['optStrg'] = isset($data['optStrg']) ? $data['optStrg'] : null;
        $this->container['optNmb'] = isset($data['optNmb']) ? $data['optNmb'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['billType'] === null) {
            $invalidProperties[] = "'billType' can't be null";
        }
        $allowedValues = $this->getBillTypeAllowableValues();
        if (!is_null($this->container['billType']) && !in_array($this->container['billType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'billType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['penaltyAmount'] === null) {
            $invalidProperties[] = "'penaltyAmount' can't be null";
        }
        if ($this->container['payOrder'] === null) {
            $invalidProperties[] = "'payOrder' can't be null";
        }
        if ($this->container['payItemId'] === null) {
            $invalidProperties[] = "'payItemId' can't be null";
        }
        if ($this->container['serviceNumber'] === null) {
            $invalidProperties[] = "'serviceNumber' can't be null";
        }
        if ($this->container['serviceid'] === null) {
            $invalidProperties[] = "'serviceid' can't be null";
        }
        if ($this->container['merchant'] === null) {
            $invalidProperties[] = "'merchant' can't be null";
        }
        if ($this->container['amountType'] === null) {
            $invalidProperties[] = "'amountType' can't be null";
        }
        $allowedValues = $this->getAmountTypeAllowableValues();
        if (!is_null($this->container['amountType']) && !in_array($this->container['amountType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'amountType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['localCur'] === null) {
            $invalidProperties[] = "'localCur' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets billType
     *
     * @return string
     */
    public function getBillType()
    {
        return $this->container['billType'];
    }

    /**
     * Sets billType
     *
     * @param string $billType 'Type classification of the bill' '\"REGULAR\" -> Regular Bill' '\"OVERDUE\" -> Late bill that is overdue'
     *
     * @return $this
     */
    public function setBillType($billType)
    {
        $allowedValues = $this->getBillTypeAllowableValues();
        if (!in_array($billType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'billType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['billType'] = $billType;

        return $this;
    }

    /**
     * Gets penaltyAmount
     *
     * @return double
     */
    public function getPenaltyAmount()
    {
        return $this->container['penaltyAmount'];
    }

    /**
     * Sets penaltyAmount
     *
     * @param double $penaltyAmount Late payment penalty amount in local currency.
     *
     * @return $this
     */
    public function setPenaltyAmount($penaltyAmount)
    {
        $this->container['penaltyAmount'] = $penaltyAmount;

        return $this;
    }

    /**
     * Gets payOrder
     *
     * @return float
     */
    public function getPayOrder()
    {
        return $this->container['payOrder'];
    }

    /**
     * Sets payOrder
     *
     * @param float $payOrder Payment order. The bill with the lowest number has to be paid first, starting with 1. If no payment order is enforced, all bills have the order 0.
     *
     * @return $this
     */
    public function setPayOrder($payOrder)
    {
        $this->container['payOrder'] = $payOrder;

        return $this;
    }

    /**
     * Gets payItemId
     *
     * @return string
     */
    public function getPayItemId()
    {
        return $this->container['payItemId'];
    }

    /**
     * Sets payItemId
     *
     * @param string $payItemId Unique  Payment Item ID for payment item identification
     *
     * @return $this
     */
    public function setPayItemId($payItemId)
    {
        $this->container['payItemId'] = $payItemId;

        return $this;
    }

    /**
     * Gets payItemDescr
     *
     * @return string
     */
    public function getPayItemDescr()
    {
        return $this->container['payItemDescr'];
    }

    /**
     * Sets payItemDescr
     *
     * @param string $payItemDescr Contains optional description about payment details (e.g. merchant provided bill types)
     *
     * @return $this
     */
    public function setPayItemDescr($payItemDescr)
    {
        $this->container['payItemDescr'] = $payItemDescr;

        return $this;
    }

    /**
     * Gets serviceNumber
     *
     * @return string
     */
    public function getServiceNumber()
    {
        return $this->container['serviceNumber'];
    }

    /**
     * Sets serviceNumber
     *
     * @param string $serviceNumber service number with merchant (e.g. meter number in bills from a utility provider or a phone number for a mobile operator)
     *
     * @return $this
     */
    public function setServiceNumber($serviceNumber)
    {
        $this->container['serviceNumber'] = $serviceNumber;

        return $this;
    }

    /**
     * Gets serviceid
     *
     * @return int
     */
    public function getServiceid()
    {
        return $this->container['serviceid'];
    }

    /**
     * Sets serviceid
     *
     * @param int $serviceid Unique  Service Identifier
     *
     * @return $this
     */
    public function setServiceid($serviceid)
    {
        $this->container['serviceid'] = $serviceid;

        return $this;
    }

    /**
     * Gets merchant
     *
     * @return string
     */
    public function getMerchant()
    {
        return $this->container['merchant'];
    }

    /**
     * Sets merchant
     *
     * @param string $merchant Unique  merchant code
     *
     * @return $this
     */
    public function setMerchant($merchant)
    {
        $this->container['merchant'] = $merchant;

        return $this;
    }

    /**
     * Gets amountType
     *
     * @return string
     */
    public function getAmountType()
    {
        return $this->container['amountType'];
    }

    /**
     * Sets amountType
     *
     * @param string $amountType 'Supported amount type for the payment of this bill:' '\"FIXED\" -> Bill needs to be paid in full, (Payment amount = bill amount provided in \"amountLocalCur\")' '\"PARTIAL\" -> Partial bill amount can be paid. (Payment amount < bill amount provided in \"amountLocalCur\"))' '\"OVERPAY\" -> More than the actual bill amount owed can be paid. (Payment amount > bill amount provided in \"amountLocalCur\"). Overpayments are subject to country specific regulations and may be limited to a certain threshold. ' '\"CUSTOM\" -> Amount can be freely entered, independent of bill amount provided in \"amountLocalCur\"'
     *
     * @return $this
     */
    public function setAmountType($amountType)
    {
        $allowedValues = $this->getAmountTypeAllowableValues();
        if (!in_array($amountType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'amountType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['amountType'] = $amountType;

        return $this;
    }

    /**
     * Gets localCur
     *
     * @return string
     */
    public function getLocalCur()
    {
        return $this->container['localCur'];
    }

    /**
     * Sets localCur
     *
     * @param string $localCur Local currency of service.(eg: XAF) (Format: ISO 4217)
     *
     * @return $this
     */
    public function setLocalCur($localCur)
    {
        $this->container['localCur'] = $localCur;

        return $this;
    }

    /**
     * Gets amountLocalCur
     *
     * @return float
     */
    public function getAmountLocalCur()
    {
        return $this->container['amountLocalCur'];
    }

    /**
     * Sets amountLocalCur
     *
     * @param float $amountLocalCur Open bill amount in local currency – (only searchable bills).
     *
     * @return $this
     */
    public function setAmountLocalCur($amountLocalCur)
    {
        $this->container['amountLocalCur'] = $amountLocalCur;

        return $this;
    }

    /**
     * Gets billNumber
     *
     * @return string
     */
    public function getBillNumber()
    {
        return $this->container['billNumber'];
    }

    /**
     * Sets billNumber
     *
     * @param string $billNumber Unique bill number in selected merchant service
     *
     * @return $this
     */
    public function setBillNumber($billNumber)
    {
        $this->container['billNumber'] = $billNumber;

        return $this;
    }

    /**
     * Gets customerNumber
     *
     * @return string
     */
    public function getCustomerNumber()
    {
        return $this->container['customerNumber'];
    }

    /**
     * Sets customerNumber
     *
     * @param string $customerNumber Customer number with merchant
     *
     * @return $this
     */
    public function setCustomerNumber($customerNumber)
    {
        $this->container['customerNumber'] = $customerNumber;

        return $this;
    }

    /**
     * Gets billMonth
     *
     * @return string
     */
    public function getBillMonth()
    {
        return $this->container['billMonth'];
    }

    /**
     * Sets billMonth
     *
     * @param string $billMonth Month of bill generation. Format: MM e.g. \"03\" for March
     *
     * @return $this
     */
    public function setBillMonth($billMonth)
    {
        $this->container['billMonth'] = $billMonth;

        return $this;
    }

    /**
     * Gets billYear
     *
     * @return string
     */
    public function getBillYear()
    {
        return $this->container['billYear'];
    }

    /**
     * Sets billYear
     *
     * @param string $billYear Year of bill generation. Format: YYYY e.g. \"2016\"
     *
     * @return $this
     */
    public function setBillYear($billYear)
    {
        $this->container['billYear'] = $billYear;

        return $this;
    }

    /**
     * Gets billDate
     *
     * @return \DateTime
     */
    public function getBillDate()
    {
        return $this->container['billDate'];
    }

    /**
     * Sets billDate
     *
     * @param \DateTime $billDate Exact date of bill generation (Format: ISO 8601)
     *
     * @return $this
     */
    public function setBillDate($billDate)
    {
        $this->container['billDate'] = $billDate;

        return $this;
    }

    /**
     * Gets billDueDate
     *
     * @return \DateTime
     */
    public function getBillDueDate()
    {
        return $this->container['billDueDate'];
    }

    /**
     * Sets billDueDate
     *
     * @param \DateTime $billDueDate Bill due date (Format: ISO 8601)
     *
     * @return $this
     */
    public function setBillDueDate($billDueDate)
    {
        $this->container['billDueDate'] = $billDueDate;

        return $this;
    }

    /**
     * Gets optStrg
     *
     * @return string
     */
    public function getOptStrg()
    {
        return $this->container['optStrg'];
    }

    /**
     * Sets optStrg
     *
     * @param string $optStrg Optional string field
     *
     * @return $this
     */
    public function setOptStrg($optStrg)
    {
        $this->container['optStrg'] = $optStrg;

        return $this;
    }

    /**
     * Gets optNmb
     *
     * @return float
     */
    public function getOptNmb()
    {
        return $this->container['optNmb'];
    }

    /**
     * Sets optNmb
     *
     * @param float $optNmb Optional number field
     *
     * @return $this
     */
    public function setOptNmb($optNmb)
    {
        $this->container['optNmb'] = $optNmb;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
